fixup! base: Add three-fingers-swipe to screenshot [1/2]
frameworks/base/services/core/java/com/android/server/policy/PhoneWindowManager.java:2639: error: method takeScreenshot in class PhoneWindowManager cannot be applied to given types;
        mSwipeToScreenshot = new SwipeToScreenshotListener(mContext, () -> takeScreenshot(
                                                                           ^
  required: int,int
  found:    int
  reason: actual and formal argument lists differ in length

needed after 71942aabb32e139d6d015ef96760be1db83baafe
Change-Id: I6968f2d252b67e54f8180ec848515191bf62c3cf